<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <LangVersion>13.0</LangVersion>
      <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="FMODAssets\Desktop\BOStuffPack.bank" />
    <None Remove="FMODAssets\Desktop\BOStuffPack.strings.bank" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Anchor.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_EOTU.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Intimidation.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Key_Blue.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Key_Purple.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Key_Red.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Key_Yellow.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Lock_Blue.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Lock_Purple.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Lock_Red.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Lock_Yellow.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_Murder.png" />
    <None Remove="Resources\AbilityIcons\AttackIcon_TwoIntoOne.png" />
    <None Remove="Resources\Items\ArtOfViolence.png" />
    <None Remove="Resources\Items\BaitPlaceholder.png" />
    <None Remove="Resources\Items\BlankBookPlaceholder.png" />
    <None Remove="Resources\Items\BlasphemyPlaceholder.png" />
    <None Remove="Resources\Items\DiceBulletsPlaceholder.png" />
    <None Remove="Resources\Items\DirtBlock.png" />
    <None Remove="Resources\Items\ElectromagnetPlaceholder.png" />
    <None Remove="Resources\Items\Eyepatch.png" />
    <None Remove="Resources\Items\failrounds.png" />
    <None Remove="Resources\Items\jester_hat.png" />
    <None Remove="Resources\Items\MusicBox.png" />
    <None Remove="Resources\Items\NegativeTeapot.png" />
    <None Remove="Resources\Items\OilPaints.png" />
    <None Remove="Resources\Items\Palette.png" />
    <None Remove="Resources\Items\RedButtonPlaceholder.png" />
    <None Remove="Resources\Items\RedMarker.png" />
    <None Remove="Resources\Items\SquirrelBomb.png" />
    <None Remove="Resources\Items\WrittenBookPlaceholder.png" />
    <None Remove="Resources\Passives\Merged.png" />
    <None Remove="Resources\Passives\Shapeshifter.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Anchor.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_EOTU.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Intimidation.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Key_Blue.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Key_Purple.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Key_Red.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Key_Yellow.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Murder.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_TwoIntoOne.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Lock_Blue.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Lock_Purple.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Lock_Red.png" />
    <EmbeddedResource Include="Resources\AbilityIcons\AttackIcon_Lock_Yellow.png" />
    <EmbeddedResource Include="Resources\Items\BaitPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\BlankBookPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\BlasphemyPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\BookmarkPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\DiceBulletsPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\DirtBlock.png" />
    <EmbeddedResource Include="Resources\Items\ElectromagnetPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\FakeGunPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\RedButtonPlaceholder.png" />
    <EmbeddedResource Include="Resources\Items\SquirrelBomb.png" />
    <EmbeddedResource Include="Resources\Items\TheHumanCondition.png" />
    <EmbeddedResource Include="Resources\Items\RedMarker.png" />
    <EmbeddedResource Include="Resources\Items\AlmightyBranch.png" />
    <EmbeddedResource Include="Resources\Items\BloodyHacksaw.png" />
    <EmbeddedResource Include="Resources\Items\ConjoinedFungi.png" />
    <EmbeddedResource Include="Resources\Items\FramedE.png" />
    <EmbeddedResource Include="Resources\Items\InstrumentsOfMurder.png" />
    <EmbeddedResource Include="Resources\Items\InterdimensionalShapeshifter.png" />
    <EmbeddedResource Include="Resources\Items\Keyring.png" />
    <EmbeddedResource Include="Resources\Items\LoudPhone.png" />
    <EmbeddedResource Include="Resources\Items\MagickalBleach.png" />
    <EmbeddedResource Include="Resources\Items\NewtonsApple.png" />
    <EmbeddedResource Include="Resources\Items\PaperCrown.png" />
    <EmbeddedResource Include="Resources\Items\Pencil.png" />
    <EmbeddedResource Include="Resources\Items\PetrifiedMedicine.png" />
    <EmbeddedResource Include="Resources\Items\Potential.png" />
    <EmbeddedResource Include="Resources\Items\RipAndTear.png" />
    <EmbeddedResource Include="Resources\Items\Survivorship.png" />
    <EmbeddedResource Include="Resources\Items\TheTideTurner.png" />
    <EmbeddedResource Include="Resources\Items\WorldShatter.png" />
    <EmbeddedResource Include="Resources\Items\WrittenBookPlaceholder.png" />
    <EmbeddedResource Include="Resources\Passives\Merged.png" />
    <EmbeddedResource Include="Resources\Passives\Shapeshifter.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\References\BrutalOrchestra\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\References\Unity\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="BrutalAPI">
      <HintPath>..\References\BrutalOrchestra\BrutalAPI.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\References\BrutalOrchestra\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>..\References\Unity\FMODUnity.dll</HintPath>
    </Reference>
    <Reference Include="Grimoire">
      <HintPath>..\Grimoire\bin\Debug\netstandard2.0\Grimoire.dll</HintPath>
    </Reference>
    <Reference Include="Marosi.SerializableCollections">
      <HintPath>..\References\Unity\Marosi.SerializableCollections.dll</HintPath>
    </Reference>
    <Reference Include="Marosi.Utility">
      <HintPath>..\References\Unity\Marosi.Utility.dll</HintPath>
    </Reference>
    <Reference Include="Pentacle">
      <HintPath>..\Pentacle\bin\Debug\netstandard2.0\Pentacle.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>..\References\Unity\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\References\Unity\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\References\Unity\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner">
      <HintPath>..\References\Unity\YarnSpinner.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner.Compiler">
      <HintPath>..\References\Unity\YarnSpinner.Compiler.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner.Unity">
      <HintPath>..\References\Unity\YarnSpinner.Unity.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="set &quot;outdir=$(OutDir)&quot;&#xD;&#xA;set &quot;assemblyname=$(AssemblyName)&quot;&#xD;&#xA;call bobuild_win.bat" Condition="$([MSBuild]::IsOSPlatform('Windows'))"/>
	<Exec Command="export OUTDIR=&quot;$(OutDir)&quot;&#xD;&#xA;export ASSEMBLYNAME=&quot;$(AssemblyName)&quot;&#xD;&#xA;./bobuild_lin.sh" Condition="$([MSBuild]::IsOSPlatform('Linux'))"/>
  </Target>

</Project>
